=== gerganakalinova/XML-XSLT-XMLSchema-Project/agencyCatalog.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="agency">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="agencyName">
					<xs:complexType>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				
				<xs:element ref="catalog" maxOccurs="unbounded" />
				<xs:element ref="countryList" />
				<xs:element ref="regionList" />
				<xs:element ref="passangersList" />
			</xs:sequence>
		</xs:complexType>
		
		<xs:key name="regionKey">
			<xs:selector xpath="./regionList/region" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:keyref name="regionRef" refer="regionKey">
			<xs:selector xpath="./catalog/excursion" />
			<xs:field xpath="@regionId" />
		</xs:keyref>
		
		<xs:key name="countryKey">
			<xs:selector xpath="./countryList/country" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:keyref name="countryRef" refer="countryKey">
			<xs:selector xpath="./catalog/excursion" />
			<xs:field xpath="@countryId" />
		</xs:keyref>
		
		<xs:key name="excursionKey">
			<xs:selector xpath="./catalog/excursion" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:keyref name="excursionRef" refer="excursionKey">
			<xs:selector xpath="./passangersList/passanger" />
			<xs:field xpath="excursionId" />
		</xs:keyref>
		
	</xs:element>
		
		
	<xs:element name="catalog">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="excursion" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="destination" type="xs:string" minOccurs="1" maxOccurs="1" />
							<xs:element name="dates">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="price" type="xs:double" minOccurs="1" maxOccurs="1" />
							<xs:element name="touristProgram" type="xs:string" minOccurs="0" maxOccurs="1" />
						</xs:sequence>
						
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="countryId" type="xs:positiveInteger" use="required" />
						<xs:attribute name="regionId" type="xs:positiveInteger" use="optional" />
						
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="countryList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="country" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="regionList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="region" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
		
	<xs:element name="passangersList">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="passanger" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firstName" type="xs:string" />
							<xs:element name="lastName" type="xs:string" />
							<xs:element name="excursionId" type="xs:positiveInteger" />
							<xs:element name="excDate" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== gerganakalinova/XML-XSLT-XMLSchema-Project/agencyCatalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="agencyCatalog.xsl"?>
<agency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="agencyCatalog.xsd">
	<agencyName name='Туристическа агенция "Ери"' />
	
	<catalog id="all">
		<excursion id="1" countryId="1" regionId="1">
			<name>СПА уикенд в Банско - 2 нощувки в СПА Ризорт Св. Иван Рилски</name>
			<description>СПА Ризорт Св. Иван Рилски се намира в най-известния български ски курорт - Банско, само на 160 км. от София. Сгушен в прегръдките на планината и само на 10 минути от ски лифта, комплексът се състои от хотел със 113 стаи, СПА Център с площ от над 1 000 кв.м. и 4 апартаментни къщи със 162 апартамента (хотелско настаняване се предлага в 80 от тях). Архитектурата е в типичния алпийски стил, съчетан с модерен интериор от дърво, камък и много светлина. Простиращ се на площ от 16 000 кв.м., целогодишният СПА Ризорт Св. Иван Рилски е охраняем комплекс от затворен тип и разполага с вътрешен двор с детска площадка, закрит паркинг и безплатен Wi-Fi на цялата си територия.</description>
			<destination>Банско</destination>
			<dates>
				<date>04.02.2022</date>
				<date>11.02.2022</date>
				<date>18.02.2022</date>
			</dates>
			<price>266</price>
			<touristProgram>1 ден
				Настаняване след 15:00 ч. Свободно време. Използване на включените в All Inclusive пакета услуги. Нощувка.
							2 ден
				Свободно време. Използване на включените в All Inclusive пакета услуги. Нощувка.
							3 ден
				Свободно време. Използване на включените в All Inclusive пакета услуги. Освобождаване на стаите до 12:00 ч.
			</touristProgram>
		</excursion>
		
		<excursion id="2" countryId="1" regionId="3">
			<name>Почивка в Лещен - 2 нощувки в хотел Лещен</name>
			<description>Хотел "Лещен" предлага на своите гости невероятен уют и спокойствие сред природата!
				Съчетава удобствата на съвременното настаняване със старобългарската архитектура и красотата на невероятните гледки в околността.
				Комплексът работи целогодишно и разполага с 45 помещения за настаняване, от които се разкрива прекрасна гледка към Родопа планина. Всички стаи са със самостоятелен санитарен възел, кабелна телевизия и парно отопление. Комфортните помещения в хотела са новообзаведени и предлагат на всички гости автентичност и удобство в едно.
				Ресторантът на хотел "Лещен" предлага вкусни ястия, приготвени от качествени продукти по старите български рецепти.
				Хотелът осигурява безплатен паркинг, открит топъл панорамен басейн (отворен за лятно ползване), релакс зона със закрит топъл панорамен басейн, вътрешно джакузи, външно джакузи, финландска сауна, парна баня и приключенски душ. Сред най-новите услуги са закрит детски кът, лоби бар, игрална зала за деца, пуро бар, кътове за четене и релакс.</description>
			<destination>Лещен</destination>
			<dates>
				<date>22.03.2022</date>
				<date>01.04.2022</date>
			</dates>
			<price>150</price>
		</excursion>
		
		<excursion id="3" countryId="1" regionId="2">
			<name>СПА уикенд в Хисаря - екскурзия с автобус</name>
			<destination>София – Копривщица – Хисаря – Старосел – Пловдив – София</destination>
			<dates>
				<date>05.02.2022</date>
				<date>24.02.2022</date>
				<date>19.03.2022</date>
			</dates>
			<price>119</price>
			<touristProgram>
				1 ден
				София – Копривщица – Хисаря

				Отпътуване в 8.00 часа от ул. "Оборище" (в участъка между пл. „Александър Невски“ и бул. „Васил Левски“) по маршрут София – Копривщица. Пешеходна обиколка на Копривщица с посещение на три къщи-музеи. Къщите са забележителни с характерната си архитектура и запазените в тях предмети: оригинално обзавеждане, стари оръжия, национални костюми, ценни бижута, образци на традиционните занаяти. Свободно време. Отпътуване за град Хисаря. Възникнал още през Античността, той се превръща в един от важните римски градове на територията на България - много са запазените обекти от онази епоха в центъра на града, като масивните укрепления, римските терми, римска гробница. Днес градът е известен със своите паркове и термални извори. Пешеходна разходка в центъра на Хисаря. Настаняване в хотел 3*. Свободно време. Нощувка.
				
				2 ден
				Хисаря – Старосел – Пловдив – София
					
				Закуска. Свободно време за ползване на СПА центъра в хотела. Отпътуване за Старосел. Пристигане в околностите на с. Старосел, където се намира най-голямото струпване на тракийски храмове и гробници в България. Посещение на основния храм в местността Четиньова могила, разположена върху голямо възвишение, което се вижда отдалеч. Отпътуване за Пловдив. Пешеходна разходка в Стария град на Пловдив - Античният театър, църквите "Св. Богородица" и "Св. Константин и Елена", Етнографският музей. Свободно време. Отпътуване за София. Пристигане на ул. "Оборище" (в участъка между пл. „Александър Невски“ и бул. „Васил Левски“) вечерта.
			</touristProgram>
		</excursion>
		
		<excursion id="4" countryId="2">
			<name>Почивка в ГЪРЦИЯ - ОСТРОВ КОРФУ - 7 нощувки - полет от София!</name>
			<description>Хотел "Bella Vista" 2* (без изхранване)

			Местоположение: разположен е в курорта Беницес на остров Корфу. Хотелът се намира на 100 м от морския бряг и на 50 м от множество ресторанти и минимаркети.

			В хотела: ресторант, рецепция, рент-а-кар.
			В стаите: самостоятелен санитарен възел, хладилник, телевизор, климатик.
			Плаж: пясъчно-чакълест, на 100 м от хотела.
			Чадъри и шезлонги на плажа: срещу допълнително заплащане - 3 евро на турист на ден.
			</description>
			<destination>София – Корфу – София</destination>
			<dates>
				<date>14.08.2022</date>
				<date>21.08.2022</date>
			</dates>
			<price>790</price>
		</excursion>
		
		<excursion id="5" countryId="2">
			<name>МАЙСКИ ПРАЗНИЦИ НА ОСТРОВ САНТОРИНИ - 3 нощувки - чартърна програма!</name>
			<description>Хотел "Veggera" 4*
				Местоположение: намира се в селището Периса, само на 20 м от пясъчния плаж и оживената крайбрежна улица в градчето.
				Хотелът: Изграден е в неокласически и цикладски стил. Разполага с 3 басейнa, хидромасажна вана, бар, кафе, ресторант.
				Стаите: отличават се със светъл интериор и са оборудвани с климатик, сателитна телевизия, самостоятелен санитарен възел, телфон, малък хладилник, сешоар, балкон.
			</description>
			<destination>София – Санторини – София</destination>
			<dates>
				<date>24.05.2022</date>
			</dates>
			<price>608</price>
			<touristProgram>1 ден
				София – Санторини
				Събиране на летище София в 08:00 ч. за директен чартърен полет на авиокомпания "Bulgaria Air" за остров Санторини в 10:00 ч. Кацане на летището на остров Санторини в 11:30 ч. Трансфер до хотела. Настаняване. Свободно време за плаж. Нощувка. (Авиокомпанията си запазва правото да прави промени в полетното разписание!)
				
				2 ден
				Санторини
				Закуска. Свободно време за плаж. По желание и предварителна заявка обиколка на остров Санторини (около 6 ч.): посещение на Пиргос - селище, изградено по склона на планината Пророк Илия, с къщи, подредени около останките от венецианска крепост; пешеходна разходка във Фира - столицата на Санторини, която отразява влиянието както на цикладската, така и на венецианската култура: търговската улица, двете катедрали (православна и католическа); свободно време с възможност за посещение на Археологическия музей, Музея на праисторическа Тира или Музея на фолклора; посещение на Имеровигли - традиционно цикладско селище, изградено по ръба на вулканичния кратер, наричано „терасата на Егейско море” поради прекрасната гледка, която се разкрива към калдерата. *препоръчителни са удобни обувки, слънчеви очила и шапки* Привечер по желание и предварителна заявка трансфер до град Иа за наблюдаване на най-красивия залез на света (около 4 ч.). *препоръчителни са удобни обувки, връхна дреха и слънчеви очила*  Връщане в хотела. Нощувка.
				
				3 ден
				Санторини
				Закуска. Свободно време за плаж. По желание екскурзия с корабче (около 6 ч.): посещение на остров Неа Камени, където може да се изкачите до кратера на все още действащия вулкан; пауза за плуване в залив около остров Палеа Камени; посещение на Тирасия - красив остров с традиционната цикладска атмосфера, където има възможност за плаж или посещение на главния град Манолас, който може да бъде достигнат пеш или на магаре - традиционен начин на придвижване на Санторини. *препоръчителни са удобни обувки, бански, слънчеви очила и шапки*  Връщане в хотела. Нощувка.
				
				4 ден
				Санторини – София
				Закуска. Освобождаване на стаите и напускане на хотела до 11.00 ч. Трансфер до летището. Отпътуване за България с директен чартърен полет на авиокомпания "Bulgaria Air" в 12:20 ч. Пристигане на летище София в 14:00 ч. (Авиокомпанията си запазва правото да прави промени в полетното разписание!)
			</touristProgram>
		</excursion>
		
		<excursion id="6" countryId="3">
			<name>Съкровищата на Испания - със самолет, на български език!</name>
			<destination>София – Малага – Коста дел Сол – Гибралтар – Кадис – Севиля – Кордоба – Толедо – Мадрид – Валенсия – Гранада – Малага – София</destination>
			<dates>
				<date>02.09.2022</date>
				<date>23.09.2022</date>
				<date>14.10.2022</date>
			</dates>
			<price>1519</price>
		</excursion>
		
		<excursion id="7" countryId="4">
			<name>Екскурзия в МЕКСИКО - Най-доброто от Мексико!</name>
			<destination>София – Мексико Сити – Теотиуакан – Каньона Сумидеро – Сан Кристобал – Паленке – Вилаермоса – Паленке – Кампече – Ушмал – град Мерида – Чичен Итца – Плая Дел Кармен – София</destination>
			<dates>
				<date>28.04.2022</date>
			</dates>
			<price>3999</price>
		</excursion>
	</catalog>
	
	<catalog id="sortedAscending" />
	<catalog id="sortedDescending" />
	<catalog id="nameSorted" />
	<catalog id="greece" />
	<catalog id="spain" />
	<catalog id="mexico" />
	<catalog id="bansko" />
	<catalog id="hisarq" />
